version: '3'
services:
  http-server:
    container_name: http-server
    image: danjellz/http-server
    ports:
      - "80:8080"
    volumes:
      - ./quote2ts/gfx:/public/
  quote2ts:
    build: ./quote2ts
    image: quote2ts
    container_name: quote2ts
    ports:
    - "10022:10022"
    entrypoint: /quote2ts/ts_rotate
