#!/bin/bash 
clear

if [ -z $PROJECT_DIR ]; then
	echo "Project dir is empty. Setting up."
  export PROJECT_DIR="./quote2ts"
  cd $(pwd ${PROJECT_DIR})
  echo "FULL PROJECT_DIR is [ $(pwd $PROJECT_DIR) ]"
echo " "
echo " PROJECT DIR [ $PROJECT_DIR ]"
echo " "
fi

export CREDENTIALS_FILE="$(find -type f -name 'creds.cfg' -print0 | xargs -0 realpath)"
export VIDEO_NAME=""
export CHOSEN_VIDEO_LINK=""
export INFO_NAME=""
export INFO_LINK="https://github.com/ovitente/quote2ts"
echo "================================================="
echo " "
echo " PROJECT DIR [ $PROJECT_DIR ]"
echo " "
echo " CRED FILE PATH [ $CREDENTIALS_FILE ]"
echo " "
echo "================================================="
TS_MANUAL="https://goo.gl/smxuVW"
VIDEO_NAME=""
VIDEOS_LIST="
illuzion-and-path
cataclisms
life
consciousness-and-personality
pyramida-experiment
pyramida-experiment-open
pyramida-experiment-effect-to-blood
allatra-new-projects-54
im-meeting
it-is-coming
invisible-world
suicide-fate-afterdeath
remote-kill-dead-resurrecting
astral
sekty
soznanie-instrument-diavola
avtoritety
o-dukhovnoy-blagodati
allatra-science
"

INFO_LIST="gitted
clickable
channel_deletion
admin-info
znaki"

function GetCredentials {
  echo " "
  echo "# GetCredentials"
    if [ -e $CREDENTIALS_FILE ]; then
        source $CREDENTIALS_FILE
    else
        echo "Cannot find credentials file - $CREDENTIALS_FILE. Creating one."
        touch $CREDENTIALS_FILE 
        if [ -e $CREDENTIALS_FILE ]; then
          printf "Please edit your new $CREDENTIALS_FILE"
        else
          printf "ERROR IN CREATING CREDS FILE."
          exit 1
        fi
        printf "export SOURCE_URL=\"ftp_url_without_http://\"\n" >> $CREDENTIALS_FILE
        printf "#export FTP_USER=\"ftp_username\"\n" >> $CREDENTIALS_FILE
        printf "#export FTP_PASSWORD=\"ftp_password\"\n" >> $CREDENTIALS_FILE

        printf "export SQUERY_URL=\"ip_or_domain_address_of_the_server\"\n" >> $CREDENTIALS_FILE
        printf "export SQUERY_PORT=\"squery_port_obviosly)\"\n" >> $CREDENTIALS_FILE
        printf "export SQUERY_SID=\"server_id\"\n" >> $CREDENTIALS_FILE
        printf "export SQUERY_USER=\"squery_username_generated_in_ts\"\n" >> $CREDENTIALS_FILE
        printf "export SQUERY_PASSWORD=\"squery_password\"\n" >> $CREDENTIALS_FILE
        exit 1
    fi
}

function GetQuotesList {
  if [ -d ${PROJECT_DIR}/gfx/generated ]; then
    quotes_array=$(ls ${PROJECT_DIR}/gfx/generated)
    status=$?
    if [ $status -ne 0 ]; then
      echo ""
      echo "There is no right path"
      echo ""
    fi
  fi
#    quotes_array=$(curl -l http://$SOURCE_URL/generated/ --user $FTP_USER:$FTP_PASSWORD | grep "$EXT")
}

function QuoteToLogo {
    export RDY_IMG="$(echo "$quotes_array" | sort -R | head -n 1)"
    expect -c '
        spawn telnet $env(SQUERY_URL) $env(SQUERY_PORT)
        send "login $env(SQUERY_USER) $env(SQUERY_PASSWORD)\r\n"
        send "use sid=$env(SQUERY_SID)\r\n"
        send "serveredit sid=$env(SQUERY_SID) virtualserver_hostbanner_gfx_url=http://$env(SOURCE_URL)/generated/$env(RDY_IMG)\r\n"
		send "quit\r\n"
		interact
'
  }

function GetVideoName {
    export VIDEO_NAME="$(echo "$VIDEOS_LIST" | sort -R | head -n 1)"
}

function VideoChose {
    GetVideoName

    case $VIDEO_NAME in
        illuzion-and-path)
            CHOSEN_VIDEO_LINK="https://youtu.be/6y4vto1ABf0"
            ;;
        cataclisms)
            CHOSEN_VIDEO_LINK="https://youtu.be/0TqI9BRGAFU"
            ;;
        life)
            CHOSEN_VIDEO_LINK="https://youtu.be/8ZiJsC11UDc"
            ;;
        consciousness-and-personality)
            CHOSEN_VIDEO_LINK="https://youtu.be/R29rL-CIsbo"
            ;;
        pyramida-experiment)
            CHOSEN_VIDEO_LINK="https://youtu.be/XANDlFVKHY4"
            ;;
        pyramida-experiment-open)
            CHOSEN_VIDEO_LINK="https://youtu.be/Kh6YP8WB4ok"
            ;;
        pyramida-experiment-effect-to-blood)
            CHOSEN_VIDEO_LINK="https://youtu.be/NBaoqm-pBXQ"
            ;;
        allatra-new-projects-54)
            CHOSEN_VIDEO_LINK="https://youtu.be/8L7ubvGDss8"
            ;;
        im-meeting)
            CHOSEN_VIDEO_LINK="https://youtu.be/hKB1u0mCBYk"
            ;;
        it-is-coming)
            CHOSEN_VIDEO_LINK="https://youtu.be/wpH3JsXsLf4"
            ;;
        invisible-world)
            CHOSEN_VIDEO_LINK="https://youtu.be/nMEPi60-Rn0"
            ;;
        suicide-fate-afterdeath)
            CHOSEN_VIDEO_LINK="https://youtu.be/gLLqpMkDSig"
            ;;
        remote-kill-dead-resurrecting)
            CHOSEN_VIDEO_LINK="https://youtu.be/abl0IrX0h38"
            ;;
        sekty)
            CHOSEN_VIDEO_LINK="https://youtu.be/vh-6_num5YA"
            ;;
        astral)
            CHOSEN_VIDEO_LINK="https://youtu.be/PS-bIc6xb70"
            ;;

        soznanie-instrument-diavola)
            CHOSEN_VIDEO_LINK="https://youtu.be/iO01oBFbFkA"
            ;;
        avtoritety)
            CHOSEN_VIDEO_LINK="https://allatra.tv/video/tajnye-gruppy-i-gubitelnost-avtoritetov"
            ;;
        o-dukhovnoy-blagodati)
            CHOSEN_VIDEO_LINK="https://youtu.be/vCtEQ-YwJiA"
            ;;
        allatra-science)
            CHOSEN_VIDEO_LINK="https://allatra.tv/category/peredachi-allatra-nauka"
            ;;            
        *)
            GetVideoName 
            VideoChose
#            CHOSEN_VIDEO_LINK="https://allatra.tv/"
            ;;
    esac
    
#    echo "* $VIDEO_NAME - $CHOSEN_VIDEO_LINK"
}

function VideosToLogo {
    if [ -z $VIDEO_NAME ]; then
#    if $VIDEO_NAME -z 2> /dev/null; then
        GetQuotesList
    fi
    expect -c '
        spawn telnet $env(SQUERY_URL) $env(SQUERY_PORT)
        send "login $env(SQUERY_USER) $env(SQUERY_PASSWORD)\r\n"
        send "use sid=$env(SQUERY_SID)\r\n"
        send "serveredit sid=$env(SQUERY_SID) virtualserver_hostbanner_gfx_url=http://$env(SOURCE_URL)/videos/png/$env(VIDEO_NAME).png virtualserver_hostbanner_url=$env(CHOSEN_VIDEO_LINK)\r\n"
		send "quit\r\n"
		interact
'
  }

function ProjectNameToLogo {
    expect -c '
        spawn telnet $env(SQUERY_URL) $env(SQUERY_PORT)
        send "login $env(SQUERY_USER) $env(SQUERY_PASSWORD)\r\n"
        send "use sid=$env(SQUERY_SID)\r\n"
        send "serveredit sid=$env(SQUERY_SID) virtualserver_hostbanner_gfx_url=http://$env(SOURCE_URL)/projects/$env(PROJECT_FILENAME)\r\n"
		send "quit\r\n"
		interact
'
     
  }

function AdminInfo {
    expect -c '
        spawn telnet $env(SQUERY_URL) $env(SQUERY_PORT)
        send "login $env(SQUERY_USER) $env(SQUERY_PASSWORD)\r\n"
        send "use sid=$env(SQUERY_SID)\r\n"
        send "serveredit sid=$env(SQUERY_SID) virtualserver_hostbanner_gfx_url=http://$env(SOURCE_URL)/info/png/$env(ADMIN_INFO) virtualserver_hostbanner_url=$env(ADMIN_INFO_LINK)\r\n"
		send "quit\r\n"
		interact
'
}

function TeamSpeakInfo {
    echo " "
    echo "# TeamSpeakInfo"
    export ADMIN_INFO="admin-info.png"
    export ADMIN_INFO_LINK="https://t.me/ivan_kostrubin"
    export INFO_NAME="$(echo "$INFO_LIST" | sort -R | head -n 1)"

    case $INFO_NAME in
        gitted)
            INFO_LINK="https://github.com/ovitente/quote2ts"
            ;;
        clickable)
            INFO_LINK=$TS_MANUAL
            ;;
        channel_deletion)
            INFO_LINK=$TS_MANUAL
            ;;
        admin-info)
            INFO_LINK=$ADMIN_INFO_LINK
            ;;
        znaki)
            INFO_LINK="https://youtu.be/gN2CAK5k9C4"
            ;;    
    esac
    expect -c '
        spawn telnet $env(SQUERY_URL) $env(SQUERY_PORT)
        send "login $env(SQUERY_USER) $env(SQUERY_PASSWORD)\r\n"
        send "use sid=$env(SQUERY_SID)\r\n"
        send "serveredit sid=$env(SQUERY_SID) virtualserver_hostbanner_gfx_url=http://$env(SOURCE_URL)/info/png/$env(INFO_NAME).png virtualserver_hostbanner_url=$env(INFO_LINK)\r\n"
		send "quit\r\n"
		interact
'
}

function init {
    min=1
    max=3

    rand="$(( $min + RANDOM % $max ))"
    case $rand in
        1)
            GetQuotesList
            QuoteToLogo > /dev/null
            echo -e "\n = Regular quote "
            ;;
        2)
            VideoChose
            VideosToLogo > /dev/null
            echo -e "\n = Videos "
            ;;
        3)
            TeamSpeakInfo > /dev/null
            echo -e "\n = INFO "
            ;;
    esac
}

### START SCRIPT ###

GetCredentials
while unlim=0
do
  (( n+=1 ))
  init
  init > /dev/null
  echo "# $n"
  sleep 5
done
